import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

abstract class AppIcons {
  static const IconData arrowForward = CupertinoIcons.forward;
  static const IconData arrowBackward = CupertinoIcons.back;
  static const IconData close = CupertinoIcons.xmark;
  static const IconData calender = CupertinoIcons.calendar;
  static const IconData search = CupertinoIcons.search;
  static const IconData eye = CupertinoIcons.eye;
  static const IconData eyeSlash = CupertinoIcons.eye_slash;
  static const IconData email = CupertinoIcons.mail;
  static const IconData arrowDown = CupertinoIcons.chevron_down;
  static const IconData profile = CupertinoIcons.person;
  static const IconData profileFilled = CupertinoIcons.person_fill;
  static const IconData edit = CupertinoIcons.square_pencil;
  static const IconData male = Icons.male;
  static const IconData female = Icons.female;
  static const IconData locationAccess = CupertinoIcons.map_pin_ellipse;
  static const IconData locationFilled = CupertinoIcons.location_solid;
  static const IconData home = CupertinoIcons.house;
  static const IconData appointment = CupertinoIcons.calendar;
  static const IconData explore = CupertinoIcons.map;
  static const IconData checked = CupertinoIcons.checkmark_circle;
  static const IconData error = CupertinoIcons.exclamationmark_octagon;
  static const IconData warning = CupertinoIcons.exclamationmark_triangle;
  static const IconData notification = CupertinoIcons.bell;
  static const IconData filters = CupertinoIcons.slider_horizontal_3;
  static const IconData call = CupertinoIcons.phone;
  static const IconData callFilled = CupertinoIcons.phone_fill;
  static const IconData time = CupertinoIcons.time;
  static const IconData timeFilled = CupertinoIcons.time_solid;
  static const IconData favorite = CupertinoIcons.suit_heart;
  static const IconData favoriteFiled = CupertinoIcons.suit_heart_fill;
  static const IconData star = CupertinoIcons.star;
  static const IconData starHalf = CupertinoIcons.star_lefthalf_fill;
  static const IconData starFilled = CupertinoIcons.star_fill;
  static const IconData verifiedCircle = CupertinoIcons.checkmark_seal;
  static const IconData verifiedCircleFilled =
      CupertinoIcons.checkmark_seal_fill;
  static const IconData settings = CupertinoIcons.gear;
  static const IconData lock = CupertinoIcons.lock;
  static const IconData logout = CupertinoIcons.square_arrow_right;
  static const IconData theme = CupertinoIcons.moon;
  static const IconData local = CupertinoIcons.globe;
  static const IconData delete = CupertinoIcons.delete;
  static const IconData password = CupertinoIcons.lock;
  static const IconData offer = CupertinoIcons.tag;
  static const IconData pay = CupertinoIcons.money_dollar;
  static const IconData wallet = Icons.wallet;
  static const IconData bookingId = CupertinoIcons.grid;
  static const IconData bookingLocation = locationFilled;
  static const IconData share = CupertinoIcons.share;
  static const IconData clinic = CupertinoIcons.house_alt;
  static const IconData patientsFilled = CupertinoIcons.group_solid;
  static const IconData experienceFilled = CupertinoIcons.bag_fill;
  static const IconData comments = CupertinoIcons.ellipses_bubble_fill;
  static const IconData lamp = CupertinoIcons.lightbulb;
  static const IconData imagePlaceHolder = CupertinoIcons.photo_on_rectangle;

}
